### ISSUE TITLE
forgotten password not working

### ISSUE THREAD

**Issue by baphled** [shenoudab/devise_couch#8]
Thanks for the latest update it helped a lot.

I've come across another issue, this time with the forgotten password functionality.

I believe that it has something to do with the latest change to the orm_adapter. But I am still getting my head around how things are tied together.

<pre><code>
/Users/baphled/.rvm/gems/ruby-1.9.2-head@cvme/bundler/gems/orm_adapter-dcf9cd38b4fc/lib/orm_adapter/adapters/couchrest_model.rb:43:in `find_first'
devise (1.2.rc) lib/devise/models/authenticatable.rb:120:in `find_or_initialize_with_errors'
devise (1.2.rc) lib/devise/models/recoverable.rb:60:in `send_reset_password_instructions'
devise (1.2.rc) app/controllers/devise/passwords_controller.rb:13:in `create'
</code></pre>

Any help would be much appreciated.

**Comment by baphled** [comment]
Sorry, this is the actual error I am getting

<pre><code>
undefined method `by_username' for # &lt;CouchRest::Model::Base::OrmAdapter:0x4bb6c9c @klass=User&gt;
</code></pre>

**Comment by baphled** [comment]
I've managed to resolve this issue. It seems that it was down to orm_adapter, which I have patched and set you a pull request.

https://github.com/shenoudab/orm_adapter/pull/1
